#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

[ -f "$SB_DATA/config.ini" ] ||\
  dockerize \
    -template /templates/config.ini.tpl:$SB_DATA/config.ini \
    echo "==> Writing $SB_DATA/config.ini from /templates/config.ini.tpl"

cd $SB_HOME
git checkout $SICKRAGE_CHANNEL
git pull
exec "/usr/bin/supervisord" "-c" "/etc/supervisor/supervisord.conf"
exit 0