#!/bin/sh
set -eo pipefail
trap "exit 0" 2 15

echo "**** Starting Sickrage (http://sickrage.github.io/) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

echo "--> Checking sickrage user ..."
if ! id sickrage >/dev/null 2>&1; then
  echo "--> Creating sickrage user and group ..."
  addgroup -g ${SB_GID} sickrage || true
  adduser -s /sbin/nologin -D -h /src -G sickrage -u ${SB_UID} sickrage
  adduser sickrage users
fi

exec $*
exit 0
