#!/bin/sh
chown -Rc sickrage:sickrage /torrents /tv_shows /downloads /data
exec /bin/escarole --branch=${SB_CHANNEL} \
  --update-interval=${UPDATE_INTERVAL} \
  --uid=${SB_UID} --gid=${SB_GID} pymedusa/Medusa sickrage
