#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

echo "**** Starting Sickrage (https://www.sickrage.tv) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

dpkg-reconfigure --frontend noninteractive tzdata

dockerize \
  -template /templates/supervisord.conf.tpl:/etc/supervisord.conf \
  -template /templates/dnsmasq.conf.tpl:/etc/dnsmasq.conf \
  echo "==> Writing configs from templates"

dnsmasq --all-servers --local-service
exec $*
exit 0