#!/bin/bash
set -eo pipefail
trap "exit 0" 2 15

echo "**** Starting Sickrage (http://sickrage.github.io/) container. Enjoy! ****"
[ -n "$OPEN_FILE_LIMIT" ] &&\
  ulimit -n $OPEN_FILE_LIMIT

t2 /templates
exec $*
exit 0
